// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/claim_item.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "eticket-api/internal/domain"
	gotann "eticket-api/pkg/gotann"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClaimItemRepository is a mock of ClaimItemRepository interface.
type MockClaimItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClaimItemRepositoryMockRecorder
}

// MockClaimItemRepositoryMockRecorder is the mock recorder for MockClaimItemRepository.
type MockClaimItemRepositoryMockRecorder struct {
	mock *MockClaimItemRepository
}

// NewMockClaimItemRepository creates a new mock instance.
func NewMockClaimItemRepository(ctrl *gomock.Controller) *MockClaimItemRepository {
	mock := &MockClaimItemRepository{ctrl: ctrl}
	mock.recorder = &MockClaimItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimItemRepository) EXPECT() *MockClaimItemRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockClaimItemRepository) Count(ctx context.Context, conn gotann.Connection) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockClaimItemRepositoryMockRecorder) Count(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClaimItemRepository)(nil).Count), ctx, conn)
}

// Delete mocks base method.
func (m *MockClaimItemRepository) Delete(ctx context.Context, conn gotann.Connection, entity *domain.ClaimItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClaimItemRepositoryMockRecorder) Delete(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClaimItemRepository)(nil).Delete), ctx, conn, entity)
}

// FindAll mocks base method.
func (m *MockClaimItemRepository) FindAll(ctx context.Context, conn gotann.Connection, limit, offset int, sort, search string) ([]*domain.ClaimItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, conn, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.ClaimItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockClaimItemRepositoryMockRecorder) FindAll(ctx, conn, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockClaimItemRepository)(nil).FindAll), ctx, conn, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockClaimItemRepository) FindByID(ctx context.Context, conn gotann.Connection, id uint) (*domain.ClaimItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.ClaimItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClaimItemRepositoryMockRecorder) FindByID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClaimItemRepository)(nil).FindByID), ctx, conn, id)
}

// Insert mocks base method.
func (m *MockClaimItemRepository) Insert(ctx context.Context, conn gotann.Connection, entity *domain.ClaimItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockClaimItemRepositoryMockRecorder) Insert(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClaimItemRepository)(nil).Insert), ctx, conn, entity)
}

// InsertBulk mocks base method.
func (m *MockClaimItemRepository) InsertBulk(ctx context.Context, conn gotann.Connection, ClaimItemes []*domain.ClaimItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, conn, ClaimItemes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockClaimItemRepositoryMockRecorder) InsertBulk(ctx, conn, ClaimItemes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockClaimItemRepository)(nil).InsertBulk), ctx, conn, ClaimItemes)
}

// Update mocks base method.
func (m *MockClaimItemRepository) Update(ctx context.Context, conn gotann.Connection, entity *domain.ClaimItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClaimItemRepositoryMockRecorder) Update(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClaimItemRepository)(nil).Update), ctx, conn, entity)
}

// UpdateBulk mocks base method.
func (m *MockClaimItemRepository) UpdateBulk(ctx context.Context, conn gotann.Connection, ClaimItemes []*domain.ClaimItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, conn, ClaimItemes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockClaimItemRepositoryMockRecorder) UpdateBulk(ctx, conn, ClaimItemes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockClaimItemRepository)(nil).UpdateBulk), ctx, conn, ClaimItemes)
}
