// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/class.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "eticket-api/internal/domain"
	gotann "eticket-api/pkg/gotann"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClassRepository is a mock of ClassRepository interface.
type MockClassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClassRepositoryMockRecorder
}

// MockClassRepositoryMockRecorder is the mock recorder for MockClassRepository.
type MockClassRepositoryMockRecorder struct {
	mock *MockClassRepository
}

// NewMockClassRepository creates a new mock instance.
func NewMockClassRepository(ctrl *gomock.Controller) *MockClassRepository {
	mock := &MockClassRepository{ctrl: ctrl}
	mock.recorder = &MockClassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassRepository) EXPECT() *MockClassRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockClassRepository) Count(ctx context.Context, conn gotann.Connection) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockClassRepositoryMockRecorder) Count(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClassRepository)(nil).Count), ctx, conn)
}

// Delete mocks base method.
func (m *MockClassRepository) Delete(ctx context.Context, conn gotann.Connection, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassRepositoryMockRecorder) Delete(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassRepository)(nil).Delete), ctx, conn, entity)
}

// FindAll mocks base method.
func (m *MockClassRepository) FindAll(ctx context.Context, conn gotann.Connection, limit, offset int, sort, search string) ([]*domain.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, conn, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockClassRepositoryMockRecorder) FindAll(ctx, conn, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockClassRepository)(nil).FindAll), ctx, conn, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockClassRepository) FindByID(ctx context.Context, conn gotann.Connection, id uint) (*domain.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClassRepositoryMockRecorder) FindByID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClassRepository)(nil).FindByID), ctx, conn, id)
}

// Insert mocks base method.
func (m *MockClassRepository) Insert(ctx context.Context, conn gotann.Connection, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockClassRepositoryMockRecorder) Insert(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClassRepository)(nil).Insert), ctx, conn, entity)
}

// InsertBulk mocks base method.
func (m *MockClassRepository) InsertBulk(ctx context.Context, conn gotann.Connection, classes []*domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, conn, classes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockClassRepositoryMockRecorder) InsertBulk(ctx, conn, classes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockClassRepository)(nil).InsertBulk), ctx, conn, classes)
}

// Update mocks base method.
func (m *MockClassRepository) Update(ctx context.Context, conn gotann.Connection, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClassRepositoryMockRecorder) Update(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClassRepository)(nil).Update), ctx, conn, entity)
}

// UpdateBulk mocks base method.
func (m *MockClassRepository) UpdateBulk(ctx context.Context, conn gotann.Connection, classes []*domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, conn, classes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockClassRepositoryMockRecorder) UpdateBulk(ctx, conn, classes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockClassRepository)(nil).UpdateBulk), ctx, conn, classes)
}
