// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/quota.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "eticket-api/internal/domain"
	gotann "eticket-api/pkg/gotann"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuotaRepository is a mock of QuotaRepository interface.
type MockQuotaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRepositoryMockRecorder
}

// MockQuotaRepositoryMockRecorder is the mock recorder for MockQuotaRepository.
type MockQuotaRepositoryMockRecorder struct {
	mock *MockQuotaRepository
}

// NewMockQuotaRepository creates a new mock instance.
func NewMockQuotaRepository(ctrl *gomock.Controller) *MockQuotaRepository {
	mock := &MockQuotaRepository{ctrl: ctrl}
	mock.recorder = &MockQuotaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRepository) EXPECT() *MockQuotaRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockQuotaRepository) Count(ctx context.Context, conn gotann.Connection) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockQuotaRepositoryMockRecorder) Count(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockQuotaRepository)(nil).Count), ctx, conn)
}

// Delete mocks base method.
func (m *MockQuotaRepository) Delete(ctx context.Context, conn gotann.Connection, entity *domain.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuotaRepositoryMockRecorder) Delete(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuotaRepository)(nil).Delete), ctx, conn, entity)
}

// FindAll mocks base method.
func (m *MockQuotaRepository) FindAll(ctx context.Context, conn gotann.Connection, limit, offset int, sort, search string) ([]*domain.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, conn, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockQuotaRepositoryMockRecorder) FindAll(ctx, conn, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockQuotaRepository)(nil).FindAll), ctx, conn, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockQuotaRepository) FindByID(ctx context.Context, conn gotann.Connection, id uint) (*domain.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockQuotaRepositoryMockRecorder) FindByID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockQuotaRepository)(nil).FindByID), ctx, conn, id)
}

// FindByScheduleID mocks base method.
func (m *MockQuotaRepository) FindByScheduleID(ctx context.Context, conn gotann.Connection, scheduleID uint) ([]*domain.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByScheduleID", ctx, conn, scheduleID)
	ret0, _ := ret[0].([]*domain.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByScheduleID indicates an expected call of FindByScheduleID.
func (mr *MockQuotaRepositoryMockRecorder) FindByScheduleID(ctx, conn, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByScheduleID", reflect.TypeOf((*MockQuotaRepository)(nil).FindByScheduleID), ctx, conn, scheduleID)
}

// FindByScheduleIDAndClassID mocks base method.
func (m *MockQuotaRepository) FindByScheduleIDAndClassID(ctx context.Context, conn gotann.Connection, scheduleID, classID uint) (*domain.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByScheduleIDAndClassID", ctx, conn, scheduleID, classID)
	ret0, _ := ret[0].(*domain.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByScheduleIDAndClassID indicates an expected call of FindByScheduleIDAndClassID.
func (mr *MockQuotaRepositoryMockRecorder) FindByScheduleIDAndClassID(ctx, conn, scheduleID, classID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByScheduleIDAndClassID", reflect.TypeOf((*MockQuotaRepository)(nil).FindByScheduleIDAndClassID), ctx, conn, scheduleID, classID)
}

// Insert mocks base method.
func (m *MockQuotaRepository) Insert(ctx context.Context, conn gotann.Connection, entity *domain.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockQuotaRepositoryMockRecorder) Insert(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQuotaRepository)(nil).Insert), ctx, conn, entity)
}

// InsertBulk mocks base method.
func (m *MockQuotaRepository) InsertBulk(ctx context.Context, conn gotann.Connection, Quotas []*domain.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, conn, Quotas)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockQuotaRepositoryMockRecorder) InsertBulk(ctx, conn, Quotas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockQuotaRepository)(nil).InsertBulk), ctx, conn, Quotas)
}

// Update mocks base method.
func (m *MockQuotaRepository) Update(ctx context.Context, conn gotann.Connection, entity *domain.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuotaRepositoryMockRecorder) Update(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuotaRepository)(nil).Update), ctx, conn, entity)
}

// UpdateBulk mocks base method.
func (m *MockQuotaRepository) UpdateBulk(ctx context.Context, conn gotann.Connection, Quotas []*domain.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, conn, Quotas)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockQuotaRepositoryMockRecorder) UpdateBulk(ctx, conn, Quotas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockQuotaRepository)(nil).UpdateBulk), ctx, conn, Quotas)
}
