// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ticket.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "eticket-api/internal/domain"
	gotann "eticket-api/pkg/gotann"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTicketRepository is a mock of TicketRepository interface.
type MockTicketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketRepositoryMockRecorder
}

// MockTicketRepositoryMockRecorder is the mock recorder for MockTicketRepository.
type MockTicketRepositoryMockRecorder struct {
	mock *MockTicketRepository
}

// NewMockTicketRepository creates a new mock instance.
func NewMockTicketRepository(ctrl *gomock.Controller) *MockTicketRepository {
	mock := &MockTicketRepository{ctrl: ctrl}
	mock.recorder = &MockTicketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketRepository) EXPECT() *MockTicketRepositoryMockRecorder {
	return m.recorder
}

// CheckIn mocks base method.
func (m *MockTicketRepository) CheckIn(ctx context.Context, conn gotann.Connection, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIn", ctx, conn, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckIn indicates an expected call of CheckIn.
func (mr *MockTicketRepositoryMockRecorder) CheckIn(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIn", reflect.TypeOf((*MockTicketRepository)(nil).CheckIn), ctx, conn, id)
}

// Count mocks base method.
func (m *MockTicketRepository) Count(ctx context.Context, conn gotann.Connection) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTicketRepositoryMockRecorder) Count(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTicketRepository)(nil).Count), ctx, conn)
}

// CountByScheduleID mocks base method.
func (m *MockTicketRepository) CountByScheduleID(ctx context.Context, conn gotann.Connection, scheduleID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByScheduleID", ctx, conn, scheduleID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByScheduleID indicates an expected call of CountByScheduleID.
func (mr *MockTicketRepositoryMockRecorder) CountByScheduleID(ctx, conn, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByScheduleID", reflect.TypeOf((*MockTicketRepository)(nil).CountByScheduleID), ctx, conn, scheduleID)
}

// CountByScheduleIDAndClassIDWithStatus mocks base method.
func (m *MockTicketRepository) CountByScheduleIDAndClassIDWithStatus(ctx context.Context, conn gotann.Connection, scheduleID, classID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByScheduleIDAndClassIDWithStatus", ctx, conn, scheduleID, classID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByScheduleIDAndClassIDWithStatus indicates an expected call of CountByScheduleIDAndClassIDWithStatus.
func (mr *MockTicketRepositoryMockRecorder) CountByScheduleIDAndClassIDWithStatus(ctx, conn, scheduleID, classID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByScheduleIDAndClassIDWithStatus", reflect.TypeOf((*MockTicketRepository)(nil).CountByScheduleIDAndClassIDWithStatus), ctx, conn, scheduleID, classID)
}

// Delete mocks base method.
func (m *MockTicketRepository) Delete(ctx context.Context, conn gotann.Connection, entity *domain.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTicketRepositoryMockRecorder) Delete(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTicketRepository)(nil).Delete), ctx, conn, entity)
}

// FindAll mocks base method.
func (m *MockTicketRepository) FindAll(ctx context.Context, conn gotann.Connection, limit, offset int, sort, search string) ([]*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, conn, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockTicketRepositoryMockRecorder) FindAll(ctx, conn, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockTicketRepository)(nil).FindAll), ctx, conn, limit, offset, sort, search)
}

// FindByBookingID mocks base method.
func (m *MockTicketRepository) FindByBookingID(ctx context.Context, conn gotann.Connection, bookingID uint) ([]*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBookingID", ctx, conn, bookingID)
	ret0, _ := ret[0].([]*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBookingID indicates an expected call of FindByBookingID.
func (mr *MockTicketRepositoryMockRecorder) FindByBookingID(ctx, conn, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBookingID", reflect.TypeOf((*MockTicketRepository)(nil).FindByBookingID), ctx, conn, bookingID)
}

// FindByClaimSessionID mocks base method.
func (m *MockTicketRepository) FindByClaimSessionID(ctx context.Context, conn gotann.Connection, sessionID uint) ([]*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClaimSessionID", ctx, conn, sessionID)
	ret0, _ := ret[0].([]*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClaimSessionID indicates an expected call of FindByClaimSessionID.
func (mr *MockTicketRepositoryMockRecorder) FindByClaimSessionID(ctx, conn, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClaimSessionID", reflect.TypeOf((*MockTicketRepository)(nil).FindByClaimSessionID), ctx, conn, sessionID)
}

// FindByID mocks base method.
func (m *MockTicketRepository) FindByID(ctx context.Context, conn gotann.Connection, id uint) (*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTicketRepositoryMockRecorder) FindByID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTicketRepository)(nil).FindByID), ctx, conn, id)
}

// FindByIDs mocks base method.
func (m *MockTicketRepository) FindByIDs(ctx context.Context, conn gotann.Connection, ids []uint) ([]*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, conn, ids)
	ret0, _ := ret[0].([]*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockTicketRepositoryMockRecorder) FindByIDs(ctx, conn, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockTicketRepository)(nil).FindByIDs), ctx, conn, ids)
}

// FindByScheduleID mocks base method.
func (m *MockTicketRepository) FindByScheduleID(ctx context.Context, conn gotann.Connection, scheduleID uint) ([]*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByScheduleID", ctx, conn, scheduleID)
	ret0, _ := ret[0].([]*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByScheduleID indicates an expected call of FindByScheduleID.
func (mr *MockTicketRepositoryMockRecorder) FindByScheduleID(ctx, conn, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByScheduleID", reflect.TypeOf((*MockTicketRepository)(nil).FindByScheduleID), ctx, conn, scheduleID)
}

// Insert mocks base method.
func (m *MockTicketRepository) Insert(ctx context.Context, conn gotann.Connection, entity *domain.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTicketRepositoryMockRecorder) Insert(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTicketRepository)(nil).Insert), ctx, conn, entity)
}

// InsertBulk mocks base method.
func (m *MockTicketRepository) InsertBulk(ctx context.Context, conn gotann.Connection, tickets []*domain.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, conn, tickets)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockTicketRepositoryMockRecorder) InsertBulk(ctx, conn, tickets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockTicketRepository)(nil).InsertBulk), ctx, conn, tickets)
}

// Update mocks base method.
func (m *MockTicketRepository) Update(ctx context.Context, conn gotann.Connection, entity *domain.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTicketRepositoryMockRecorder) Update(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTicketRepository)(nil).Update), ctx, conn, entity)
}

// UpdateBulk mocks base method.
func (m *MockTicketRepository) UpdateBulk(ctx context.Context, conn gotann.Connection, tickets []*domain.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, conn, tickets)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockTicketRepositoryMockRecorder) UpdateBulk(ctx, conn, tickets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockTicketRepository)(nil).UpdateBulk), ctx, conn, tickets)
}
