// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/booking.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "eticket-api/internal/domain"
	gotann "eticket-api/pkg/gotann"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockBookingRepository) Count(ctx context.Context, conn gotann.Connection) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockBookingRepositoryMockRecorder) Count(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockBookingRepository)(nil).Count), ctx, conn)
}

// Delete mocks base method.
func (m *MockBookingRepository) Delete(ctx context.Context, conn gotann.Connection, entity *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookingRepositoryMockRecorder) Delete(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookingRepository)(nil).Delete), ctx, conn, entity)
}

// FindAll mocks base method.
func (m *MockBookingRepository) FindAll(ctx context.Context, conn gotann.Connection, limit, offset int, sort, search string) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, conn, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBookingRepositoryMockRecorder) FindAll(ctx, conn, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBookingRepository)(nil).FindAll), ctx, conn, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockBookingRepository) FindByID(ctx context.Context, conn gotann.Connection, id uint) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBookingRepositoryMockRecorder) FindByID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBookingRepository)(nil).FindByID), ctx, conn, id)
}

// FindByOrderID mocks base method.
func (m *MockBookingRepository) FindByOrderID(ctx context.Context, conn gotann.Connection, id string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", ctx, conn, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockBookingRepositoryMockRecorder) FindByOrderID(ctx, conn, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockBookingRepository)(nil).FindByOrderID), ctx, conn, id)
}

// Insert mocks base method.
func (m *MockBookingRepository) Insert(ctx context.Context, conn gotann.Connection, entity *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockBookingRepositoryMockRecorder) Insert(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockBookingRepository)(nil).Insert), ctx, conn, entity)
}

// InsertBulk mocks base method.
func (m *MockBookingRepository) InsertBulk(ctx context.Context, conn gotann.Connection, bookings []*domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, conn, bookings)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockBookingRepositoryMockRecorder) InsertBulk(ctx, conn, bookings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockBookingRepository)(nil).InsertBulk), ctx, conn, bookings)
}

// Update mocks base method.
func (m *MockBookingRepository) Update(ctx context.Context, conn gotann.Connection, entity *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBookingRepositoryMockRecorder) Update(ctx, conn, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookingRepository)(nil).Update), ctx, conn, entity)
}

// UpdateBulk mocks base method.
func (m *MockBookingRepository) UpdateBulk(ctx context.Context, conn gotann.Connection, bookings []*domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", ctx, conn, bookings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockBookingRepositoryMockRecorder) UpdateBulk(ctx, conn, bookings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBulk), ctx, conn, bookings)
}
