// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/class.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "eticket-api/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockClassRepository is a mock of ClassRepository interface.
type MockClassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClassRepositoryMockRecorder
}

// MockClassRepositoryMockRecorder is the mock recorder for MockClassRepository.
type MockClassRepositoryMockRecorder struct {
	mock *MockClassRepository
}

// NewMockClassRepository creates a new mock instance.
func NewMockClassRepository(ctrl *gomock.Controller) *MockClassRepository {
	mock := &MockClassRepository{ctrl: ctrl}
	mock.recorder = &MockClassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassRepository) EXPECT() *MockClassRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockClassRepository) Count(db *gorm.DB) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", db)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockClassRepositoryMockRecorder) Count(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClassRepository)(nil).Count), db)
}

// Delete mocks base method.
func (m *MockClassRepository) Delete(db *gorm.DB, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassRepositoryMockRecorder) Delete(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassRepository)(nil).Delete), db, entity)
}

// FindAll mocks base method.
func (m *MockClassRepository) FindAll(db *gorm.DB, limit, offset int, sort, search string) ([]*domain.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockClassRepositoryMockRecorder) FindAll(db, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockClassRepository)(nil).FindAll), db, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockClassRepository) FindByID(db *gorm.DB, id uint) (*domain.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", db, id)
	ret0, _ := ret[0].(*domain.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClassRepositoryMockRecorder) FindByID(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClassRepository)(nil).FindByID), db, id)
}

// Insert mocks base method.
func (m *MockClassRepository) Insert(db *gorm.DB, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockClassRepositoryMockRecorder) Insert(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClassRepository)(nil).Insert), db, entity)
}

// InsertBulk mocks base method.
func (m *MockClassRepository) InsertBulk(db *gorm.DB, classes []*domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", db, classes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockClassRepositoryMockRecorder) InsertBulk(db, classes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockClassRepository)(nil).InsertBulk), db, classes)
}

// Update mocks base method.
func (m *MockClassRepository) Update(db *gorm.DB, entity *domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClassRepositoryMockRecorder) Update(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClassRepository)(nil).Update), db, entity)
}

// UpdateBulk mocks base method.
func (m *MockClassRepository) UpdateBulk(db *gorm.DB, classes []*domain.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", db, classes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockClassRepositoryMockRecorder) UpdateBulk(db, classes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockClassRepository)(nil).UpdateBulk), db, classes)
}
