// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/schedule.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "eticket-api/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockScheduleRepository) Count(db *gorm.DB) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", db)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockScheduleRepositoryMockRecorder) Count(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockScheduleRepository)(nil).Count), db)
}

// Delete mocks base method.
func (m *MockScheduleRepository) Delete(db *gorm.DB, entity *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleRepositoryMockRecorder) Delete(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleRepository)(nil).Delete), db, entity)
}

// FindActiveSchedule mocks base method.
func (m *MockScheduleRepository) FindActiveSchedule(db *gorm.DB) ([]*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveSchedule", db)
	ret0, _ := ret[0].([]*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveSchedule indicates an expected call of FindActiveSchedule.
func (mr *MockScheduleRepositoryMockRecorder) FindActiveSchedule(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).FindActiveSchedule), db)
}

// FindAll mocks base method.
func (m *MockScheduleRepository) FindAll(db *gorm.DB, limit, offset int, sort, search string) ([]*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockScheduleRepositoryMockRecorder) FindAll(db, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockScheduleRepository)(nil).FindAll), db, limit, offset, sort, search)
}

// FindAllScheduled mocks base method.
func (m *MockScheduleRepository) FindAllScheduled(db *gorm.DB) ([]*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllScheduled", db)
	ret0, _ := ret[0].([]*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllScheduled indicates an expected call of FindAllScheduled.
func (mr *MockScheduleRepositoryMockRecorder) FindAllScheduled(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllScheduled", reflect.TypeOf((*MockScheduleRepository)(nil).FindAllScheduled), db)
}

// FindByID mocks base method.
func (m *MockScheduleRepository) FindByID(db *gorm.DB, id uint) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", db, id)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockScheduleRepositoryMockRecorder) FindByID(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockScheduleRepository)(nil).FindByID), db, id)
}

// Insert mocks base method.
func (m *MockScheduleRepository) Insert(db *gorm.DB, entity *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockScheduleRepositoryMockRecorder) Insert(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockScheduleRepository)(nil).Insert), db, entity)
}

// InsertBulk mocks base method.
func (m *MockScheduleRepository) InsertBulk(db *gorm.DB, schedules []*domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", db, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockScheduleRepositoryMockRecorder) InsertBulk(db, schedules interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockScheduleRepository)(nil).InsertBulk), db, schedules)
}

// Update mocks base method.
func (m *MockScheduleRepository) Update(db *gorm.DB, entity *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduleRepositoryMockRecorder) Update(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduleRepository)(nil).Update), db, entity)
}

// UpdateBulk mocks base method.
func (m *MockScheduleRepository) UpdateBulk(db *gorm.DB, schedules []*domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", db, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockScheduleRepositoryMockRecorder) UpdateBulk(db, schedules interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockScheduleRepository)(nil).UpdateBulk), db, schedules)
}
