// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ship.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "eticket-api/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockShipRepository is a mock of ShipRepository interface.
type MockShipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShipRepositoryMockRecorder
}

// MockShipRepositoryMockRecorder is the mock recorder for MockShipRepository.
type MockShipRepositoryMockRecorder struct {
	mock *MockShipRepository
}

// NewMockShipRepository creates a new mock instance.
func NewMockShipRepository(ctrl *gomock.Controller) *MockShipRepository {
	mock := &MockShipRepository{ctrl: ctrl}
	mock.recorder = &MockShipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipRepository) EXPECT() *MockShipRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockShipRepository) Count(db *gorm.DB) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", db)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockShipRepositoryMockRecorder) Count(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockShipRepository)(nil).Count), db)
}

// Delete mocks base method.
func (m *MockShipRepository) Delete(db *gorm.DB, entity *domain.Ship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShipRepositoryMockRecorder) Delete(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShipRepository)(nil).Delete), db, entity)
}

// FindAll mocks base method.
func (m *MockShipRepository) FindAll(db *gorm.DB, limit, offset int, sort, search string) ([]*domain.Ship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, limit, offset, sort, search)
	ret0, _ := ret[0].([]*domain.Ship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShipRepositoryMockRecorder) FindAll(db, limit, offset, sort, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShipRepository)(nil).FindAll), db, limit, offset, sort, search)
}

// FindByID mocks base method.
func (m *MockShipRepository) FindByID(db *gorm.DB, id uint) (*domain.Ship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", db, id)
	ret0, _ := ret[0].(*domain.Ship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShipRepositoryMockRecorder) FindByID(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShipRepository)(nil).FindByID), db, id)
}

// Insert mocks base method.
func (m *MockShipRepository) Insert(db *gorm.DB, entity *domain.Ship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockShipRepositoryMockRecorder) Insert(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockShipRepository)(nil).Insert), db, entity)
}

// InsertBulk mocks base method.
func (m *MockShipRepository) InsertBulk(db *gorm.DB, ships []*domain.Ship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", db, ships)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockShipRepositoryMockRecorder) InsertBulk(db, ships interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockShipRepository)(nil).InsertBulk), db, ships)
}

// Update mocks base method.
func (m *MockShipRepository) Update(db *gorm.DB, entity *domain.Ship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShipRepositoryMockRecorder) Update(db, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShipRepository)(nil).Update), db, entity)
}

// UpdateBulk mocks base method.
func (m *MockShipRepository) UpdateBulk(db *gorm.DB, ships []*domain.Ship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBulk", db, ships)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBulk indicates an expected call of UpdateBulk.
func (mr *MockShipRepositoryMockRecorder) UpdateBulk(db, ships interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBulk", reflect.TypeOf((*MockShipRepository)(nil).UpdateBulk), db, ships)
}
