version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: umbresGurgur
      POSTGRES_DB: tikethebat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tikethebat  # Join shared network so app container can connect

volumes:
  pgdata:

networks:
  tikethebat:
    external: true  # Use the same manually created or CI-created network
