server:
  port: 8080

auth:
  secret_key: "salty_chocolate"
  access_token_expiry: "15m"
  refresh_token_expiry: "24h"

database:
  host: localhost
  port: 5432
  name: eticket-api
  user: postgres
  password: umbresgurgur
  sslmode: disable

