server:
  port: 8080

auth:
  secret_key: "salty_chocolate"
  AccessTokenExpiry: 15 #minutes
  RefreshTokenExpiry: 1 #days

database:
  host: localhost
  port: 5432
  name: eticket-api
  user: postgres
  password: umbresgurgur
  sslmode: disable

