server:
  port: 8080

auth:
  secret_key: "salty_chocolate"
  access_token_expiry: "15m" #minutes
  refresh_token_expiry: "24h" #days

database:
  host: aws-0-ap-southeast-1.pooler.supabase.com
  port: 5432
  name: postgres
  user: postgres.dnhjxuwlhfwxbkbbhrwq
  password: UmbresGurgur1
  sslmode: disable
