// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"eticket-api/config"
	"eticket-api/internal/injector/module"
	"eticket-api/pkg/casbinx"
	"eticket-api/pkg/db/postgres"
	"eticket-api/pkg/jwt"
	"eticket-api/pkg/utils/tx"
)

// Injectors from wire.go:

func InitializeContainer(cfg *config.Config) (*Container, error) {
	db, err := postgres.New(cfg)
	if err != nil {
		return nil, err
	}
	txManager := tx.New(db)
	tokenManager := jwt.New(cfg)
	enforcer := casbinx.NewEnforcer(db)
	repositoryModule := module.NewRepositoryModule()
	usecaseModule := module.NewUsecaseModule(txManager, repositoryModule, tokenManager)
	controllerModule := module.NewControllerModule(cfg, usecaseModule, tokenManager)
	container := NewContainer(cfg, db, txManager, tokenManager, enforcer, repositoryModule, usecaseModule, controllerModule)
	return container, nil
}
