name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/tikethebat:${IMAGE_TAG} .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/tikethebat:${IMAGE_TAG}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          location: southeastasia  
          imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/tikethebat:${{ github.sha }}
          environmentVariables: >
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}
            REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }}
            TRIPAY_API_KEY=${{ secrets.TRIPAY_API_KEY }}
            TRIPAY_PRIVATE_API_KEY=${{ secrets.TRIPAY_PRIVATE_API_KEY }}
            TRIPAY_MERCHANT_CODE=${{ secrets.TRIPAY_MERCHANT_CODE }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_SSLMODE=${{ secrets.DATABASE_SSLMODE }}


          # Use the secure secrets here
          registryUrl: ${{ secrets.ACR_NAME }}.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }} 
          registryPassword: ${{ secrets.ACR_PASSWORD }} 
