name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:${{ github.sha }}
